/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],

  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: "var(--surface)",
        "surface-elevated": "var(--surface-elevated)",
        "surface-hover": "var(--surface-hover)",
        "surface-active": "var(--surface-active)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-inverse": "var(--text-inverse)",
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-foreground": "var(--primary-foreground)",
        "accent-brand": "var(--accent-brand)",
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        info: "var(--info)",
        destructive: "var(--destructive)",
        ring: "var(--ring)",
        button: "var(--button)",
        "button-foreground": "var(--button-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        input: "var(--input)",
        "message-sent": "var(--message-sent)",
        "message-received": "var(--message-received)",
        "chat-background": "var(--chat-background)",
        "sidebar-background": "var(--sidebar-background)",
        "sidebar-button-bg": "var(--sidebar-button-bg)",
        "sidebar-button-hover": "var(--sidebar-button-hover)",
        "sidebar-button-active": "var(--sidebar-button-active)",
      },
      fontFamily: {
        chillax: ["var(--font-chillax)"],
      },
    },
  },

  plugins: [],
};
